import {StyleSheet} from "react-native"

 export const styles = StyleSheet.create({
    parent: {
      flex: 1,
      backgroundColor: 'white',
    },
    header: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 16,
      paddingHorizontal: 23,
      borderBottomWidth: 1,
      borderBottomColor: '#EFEEF0',
    },
    headerText: {
      color: 'black',
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 22,
      fontFamily: 'Inter-Medium',
    },
    headerText1: {
      color: '#180E25',
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 22,
      fontFamily: 'Inter-Medium',
    },
    headerChild: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 15,
    },
    button: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
      marginTop: 24,
      gap: 10,
      paddingVertical: 8,
      borderColor: '#613EEA',
      borderWidth: 1,
      borderRadius: 25,
    },
    buttonText: {
      color: '#613EEA',
      fontSize: 16,
      fontWeight: '500',
      lineHeight: 22,
      fontFamily: 'Inter-Medium',
    },
    buttonParent: {},
    profileSec: {
      display: 'flex',
      alignItems: 'center',
      borderBottomColor: '#EFEEF0',
      borderBottomWidth: 1,
      paddingBottom: 24,
      marginHorizontal: 16,
    },
    emailLable: {
      fontSize: 16,
      lineHeight: 38,
      fontWeight: '500',
      fontFamily: 'Inter-Medium',
      color: '#180E25',
      marginTop: 26,
      marginHorizontal: 16,
    },
    emailInput: {
      color: 'gray',
      borderColor: '#C8C5CB',
      paddingHorizontal: 16,
      borderRadius: 8,
      borderWidth: 1,
      marginHorizontal: 16,
    },
    text: {
      fontSize: 12,
      lineHeight: 14,
      fontWeight: '400',
      fontFamily: 'Inter-Medium',
      color: '#C8C5CB',
      marginTop: 12,
      marginHorizontal: 16,
    },
    buttonText1: {fontSize: 16, lineHeight: 22, color: 'white'},
    button1: {
      backgroundColor: '#613EEA',
      display: 'flex',
      flexDirection: 'row-reverse',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderRadius: 50,
      paddingVertical: 16,
      paddingHorizontal: 24,
      marginTop: 80,
      marginHorizontal: 16,
    },
    buttonContainer: {
      flexDirection: 'column',
      marginVertical: 8,
    },
    imageContainer: {
      marginVertical: 10,
      alignItems: 'center',
    },
    image: {
      height: 120,
      width: 120,
      marginTop: 24,
      borderRadius: 80,
    },
  });
  